<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Netsol
 * @package     Netsol_Seasons
 * @copyright   Copyright (c) 2016 Netsolutions India (http://www.netsolutions.in)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */ 
$paSeasonBannerCollection =  $this->predictiveSeasonBannerBlock();
$enabled = Mage::helper('seasons/data')->isEnabled();
$silderEnabled = Mage::helper('seasons/data')->getSeasonSliderEnabled();
if($enabled == 1 && count($paSeasonBannerCollection) && $silderEnabled == 1){ 
?>
<div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 1300px; height: 500px; overflow: hidden; visibility: hidden;"><!-- Loading Screen -->
	<div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
		<div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
		<div style="position:absolute;display:block;background:url('<?php echo $this->getSkinUrl('images/netsol/seasons/img/loading.gif');?>') no-repeat center center;top:0px;left:0px;width:100%;height:100%;">
		</div>
	</div>
	<div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 1300px; height: 500px; overflow: hidden;">
		
		<?php foreach($paSeasonBannerCollection as $paSeasonBanner) { ?>
			<?php if($paSeasonBanner->getBannerImage() != '' && $paSeasonBanner->getStatus() == 1) { ?>
			<div data-p="225.00" style="display: none;">
				<?php if($paSeasonBanner->getWeblink() != '') { ?>
				<a href="<?php echo $paSeasonBanner->getWeblink();  ?>" >
				<?php } ?>
					<img data-u="image" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$paSeasonBanner->getBannerImage();?>" />
				<?php if($paSeasonBanner->getWeblink() != '') { ?>
				</a>
				<?php } ?>
			</div>
			<?php } ?>
		<?php } ?>

	</div>
	<div data-u="navigator" class="jssorb05" style="bottom:16px;right:16px;" data-autocenter="1"><!-- bullet navigator item prototype -->
				<div data-u="prototype" style="width:16px;height:16px;"></div>
	</div>
	<!-- Arrow Navigator --><span data-u="arrowleft" class="jssora22l" style="top:0px;left:12px;width:40px;height:58px;" data-autocenter="2"></span><span data-u="arrowright" class="jssora22r" style="top:0px;right:12px;width:40px;height:58px;" data-autocenter="2"></span>
</div>
<script>jssor_1_slider_init();</script>
<?php } ?>
